project:
  type: book
  output-dir: docs

book:
  title: "R for Byplankontoret"
  author: "Håvard Karlsen"
  date: last-modified
  date-format: "YYYY-MM-DD"
  cover-image: img/ryoji-iwata-n31JPLu8_Pw-unsplash.jpg
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Fundamentale konsepter"
      chapters:
        - omR.qmd
        - pakker.qmd
        - grunnleggende.qmd
    - import-export.qmd
    - inspisere.qmd
    - pivot.qmd
    - filter.qmd
    - transformasjoner.qmd
    - joins.qmd
    - arbeidsprosess.qmd
    - feil.qmd
    - references.qmd
    - praktisk-eksempel.qmd

crossref:
  fig-prefix: Figur   
  fig-title: Figur
  sec-prefix: Kapittel


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

