project:
  type: book

book:
  title: "R for Byplankontoret"
  author: "Håvard Karlsen"
  #date: 2023-03-24
  date: last-modified
  date-format: "YYYY-MM-DD"
  cover-image: img/ryoji-iwata-n31JPLu8_Pw-unsplash.jpg
  chapters:
    - index.qmd
    - intro.qmd
    - omR.qmd
    - pakker.qmd
    - grunnleggende.qmd
    - import-export.qmd
    - inspisere.qmd
    - pivot.qmd
    - filter.qmd
    - transformasjoner.qmd
    - joins.qmd
    - arbeidsprosess.qmd
    - feil.qmd
    - references.qmd

crossref:
  fig-prefix: Figur   # (default is "Figure")
  fig-title: Figur
  sec-prefix: Kapittel


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

