project:
  type: book

book:
  title: "R for Byplankontoret"
  author: "Håvard Karlsen"
  date: 2023-03-24
  chapters:
    - index.qmd
    - intro.qmd
    - omR.qmd
    - pakker.qmd
    - grunnleggende.qmd
    - import-export.qmd
    - inspisere.qmd
    - pivot.qmd
    - filter.qmd
    - transformasjoner.qmd
    - joins.qmd
    - feil.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

