# Introduksjon

Tanken bak denne dokumentasjonen er å legge best mulig til rette for at dere på Byplankontoret skal fortsette å bruke skriptene jeg utvikla, og kanskje til og med ta i bruk R mer på egen hånd. Derfor har jeg utforma dokumentasjonen slik: 

Første del handler om grunnleggende kunnskaper man trenger om R. Her forsøkte jeg å komprimere alt jeg skulle ønske jeg visste om R da jeg starta ned til dets essens. En del av dette vil dere ikke se igjen seinere, fordi det blir avløst av funksjonalitet fra `tidyverse`. Likevel er det greit å ha en ide om hvordan `base R` opererer og funker, siden alt er bygd på dette. 

I andre del av pamfletten går jeg gjennom de funksjonene jeg bruker oftest. Dette er funksjoner som jeg ikke ville forklart grundig i skripta jeg har laga fordi funksjonene er så grunnleggende. En gang må man lære det grunnleggende, og det kan være her. Dere vil se disse funksjonene bli brukt til stadighet i skriptene mine, så det vil finnes mange eksempler rundt omkring.

Dere vil sikkert oppleve at detaljnivået i teksten varierer fra for inngående til for løst omtalt. Målet mitt var å vise litt av alt. Hvis dere har sett eksempler på noe håper jeg dere kan tenke dere fram til en fortsettelse eller utvidelse av materialet. Her er det viktig å kunne **google** seg fram til svaret sitt, basert på noen antakelser. Formen til teksten er nok prega av at jeg sjøl lærer best av eksempler. Dermed er jeg nok noen ganger for slapp med å forklare nøyaktig hva en funksjon gjør, fordi jeg tenker dere vil skjønne det når dere kjører koden. 

I eksemplene bruker jeg aldri data fra Byplankontoret direkte. Jeg bruker enten data som ligger i R-pakker, eller jeg simulerer data som likner på noe vi kunne ha brukt. 
## Hvordan bruke denne pamfletten

Du kan lese om programmering, men vit at forståelsen ikke kommer før du *gjør* programmering. Slik er det med R også. Derfor anbefaler jeg deg å kjøre koden som jeg oppgir i kodeblokkene. Da blir det enklere å følge med på hva som skjer.

```{r}
# Dette er en kodeblokk.
```

Du trenger ikke lese fra "perm til perm", og kan hoppe rundt slik du føler for. Bare vit at jeg har skrevet dette hovedsaklig i kronologisk rekkefølge, så funksjoner blir vanligvis introdusert første gang de nevnes. Likevel er det en del repetisjon her og der. 


## Tidshorisont

Denne dokumentasjonen blei til i mars 2023. Koden forventes å kunne kjøres uten problemer en stund framover. Som jeg nevner i @sec-versjering vil kanskje framtidige versjoner av R og `tidyverse` gjøre endringer som påvirker koden min her. Om dere får tak i samme versjon av R og `tidyverse` vil dere unngå eventuelle problemer forbundet med dette. 

---

Lykke til!

*Håvard*

`r Sys.Date()`
